# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-03-13 20:53
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RunSQL("DROP PROCEDURE IF EXISTS SP_MESSAGES_LIST;"),
        migrations.RunSQL("DROP FUNCTION IF EXISTS  get_display_name ;"),
        migrations.RunSQL(
            """ CREATE FUNCTION get_display_name(nick VARCHAR(250), first_name VARCHAR(250), last_name VARCHAR(250), agent_firstname VARCHAR(250),  agent_lastname VARCHAR(250))
                RETURNS VARCHAR(250)
                BEGIN
                    DECLARE display_name VARCHAR(250);
                    IF LENGTH(nick)>0 THEN SET display_name = nick;
                    ELSEIF LENGTH(first_name) > 0 THEN SET display_name = CONCAT(first_name, ' ', last_name);
                    ELSE SET display_name =  CONCAT(agent_firstname, ' ', agent_lastname);
                    END IF;
                    RETURN display_name;
                END ;
                """),

        migrations.RunSQL(
            # 'source dump.sql'
            """
            CREATE PROCEDURE SP_MESSAGES_LIST(IN flag INT, IN p_user_id INT, IN p_aux_1 INT, IN p_aux_2 INT, IN p_aux_3 VARCHAR(20))
BEGIN DECLARE v_id_specialist INT;
    DECLARE v_total INT;
    DECLARE v_id INT;
    IF flag = 1
    THEN SELECT
           max(m.id)         AS id,
           u.photo,
           u.nick,
           max(m.created_at) AS date,
           q.title,
           m.message,
           q.client_id       AS client,
           q.specialist_id   AS specialist,
           count(1)          AS total
         FROM api_message m
           JOIN api_query q ON m.query_id = q.id
           JOIN api_client c ON q.client_id = c.user_ptr_id
           JOIN api_user u ON c.user_ptr_id = u.id
         WHERE q.specialist_id = p_user_id
         GROUP BY q.client_id
         ORDER BY 4;
    ELSEIF flag = 2
      THEN SELECT
             max(m.id)
           INTO v_id
           FROM api_message m
             JOIN api_query q ON m.query_id = q.id
           WHERE q.client_id = p_user_id
           ORDER BY m.created_at;
        SELECT DISTINCT
          q.id         AS id,
          u.photo,
          get_display_name(u.nick, u.first_name, u.last_name, c.agent_firstname, c.agent_lastname ) AS display_name,
          m.created_at    AS date,
          q.title,
          m.message,
          q.client_id     AS client,
          q.specialist_id AS specialist
        FROM api_message m
          JOIN api_query q ON m.query_id = q.id
          JOIN api_client c ON q.client_id = c.user_ptr_id
          JOIN api_user u ON c.user_ptr_id = u.id
        WHERE m.id = v_id;
    ELSE SELECT
           "None" AS id,
           "None" AS photo,
           "None" AS nick,
           "None" AS date,
           "None" AS title,
           "None" AS message,
           "None" AS client,
           "None" AS specialist,
           "None" AS total; END IF;
  END
 """   )
    ]
