# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-07-13 13:49
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='queryplansmanage',
            name='new_acquired_plan',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='api.QueryPlansAcquired'),
        ),
        migrations.AlterField(
            model_name='queryplansmanage',
            name='status',
            field=models.PositiveIntegerField(choices=[(1, 'Active'), (2, 'Deactive'), (3, 'Processing')]),
        ),
    ]
