# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-25 23:22
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20171023_1141'),
    ]

    operations = [
        migrations.CreateModel(
            name='products_seller_no_billable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('query_amount_no_billable', models.IntegerField()),
                ('query_amount_no_billable_available', models.IntegerField()),
                ('date', models.DateField(unique=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='paymenttype',
            name='api_client',
        ),
        migrations.RemoveField(
            model_name='paymenttype',
            name='tablename',
        ),
        migrations.RemoveField(
            model_name='product',
            name='purchases',
        ),
        migrations.RemoveField(
            model_name='seller',
            name='count_month_contacts',
        ),
        migrations.RemoveField(
            model_name='seller',
            name='count_month_plans',
        ),
        migrations.RemoveField(
            model_name='seller',
            name='count_month_promotional',
        ),
        migrations.RemoveField(
            model_name='seller',
            name='monthly_promotional_plans',
        ),
        migrations.AddField(
            model_name='fee',
            name='api_client',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='fee',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='fee',
            name='datetime_payment',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='fee',
            name='status',
            field=models.CharField(choices=[('1', 'Wait'), ('2', 'Ready')], default=1, max_length=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='fee',
            name='tablename',
            field=models.CharField(max_length=17, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='is_billable',
            field=models.BooleanField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='purchase',
            name='code',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='purchase',
            name='product',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='api.Product'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='purchase',
            name='query_amount',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='quota',
            name='count_contacts',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='products_seller_no_billable',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api.Product'),
        ),
        migrations.AddField(
            model_name='products_seller_no_billable',
            name='seller',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api.Seller'),
        ),
        migrations.AddField(
            model_name='product',
            name='seller',
            field=models.ManyToManyField(through='api.products_seller_no_billable', to='api.Seller'),
        ),
    ]
