# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-02 23:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20170925_2332'),
    ]

    operations = [
        migrations.AlterField(
            model_name='specialist',
            name='cv',
            field=models.CharField(max_length=150, null=True),
        ),
    ]
