# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-03-13 20:53
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('api', '0023_auto_20180313_0944'),
    ]

    operations = [
        migrations.RunSQL("DROP PROCEDURE IF EXISTS SP_MESSAGES_LIST;"),
        migrations.RunSQL(
            # 'source dump.sql'
            """
            CREATE PROCEDURE SP_MESSAGES_LIST(IN flag INT, IN p_user_id INT, IN p_aux_1 INT, IN p_aux_2 INT, IN p_aux_3 VARCHAR(20))
BEGIN DECLARE v_id_specialist INT;
    DECLARE v_total INT;
    DECLARE v_id INT;
    IF flag = 1
    THEN SELECT
           max(m.id)         AS id,
           u.photo,
           u.nick,
           max(m.created_at) AS date,
           q.title,
           m.message,
           q.client_id       AS client,
           q.specialist_id   AS specialist,
           count(1)          AS total
         FROM api_message m
           JOIN api_query q ON m.query_id = q.id
           JOIN api_client c ON q.client_id = c.user_ptr_id
           JOIN api_user u ON c.user_ptr_id = u.id
         WHERE q.specialist_id = p_user_id
         GROUP BY q.client_id
         ORDER BY 4;
    ELSEIF flag = 2
      THEN SELECT
             max(m.id)
           INTO v_id
           FROM api_message m
             JOIN api_query q ON m.query_id = q.id
           WHERE q.client_id = p_user_id
           ORDER BY m.created_at;
        SELECT DISTINCT
          q.id         AS id,
          u.photo,
          IF(LENGTH(u.nick)>0, u.nick, CONCAT(u.first_name, ' ', u.last_name) ) as display_name,
          m.created_at    AS date,
          q.title,
          m.message,
          q.client_id     AS client,
          q.specialist_id AS specialist
        FROM api_message m
          JOIN api_query q ON m.query_id = q.id
          JOIN api_client c ON q.client_id = c.user_ptr_id
          JOIN api_user u ON c.user_ptr_id = u.id
        WHERE m.id = v_id;
    ELSE SELECT
           "None" AS id,
           "None" AS photo,
           "None" AS nick,
           "None" AS date,
           "None" AS title,
           "None" AS message,
           "None" AS client,
           "None" AS specialist,
           "None" AS total; END IF;
  END
 """    )
    ]
