# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-10-04 20:02
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_message_uploaded'),
    ]

    operations = [
        migrations.CreateModel(
            name='MatchFiles',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_url', models.CharField(max_length=500)),
                ('content_type', models.PositiveIntegerField(choices=[(1, 'Text'), (2, 'Image'), (3, 'Video'), (4, 'Voice'), (5, 'Document')])),
            ],
        ),
        migrations.CreateModel(
            name='MatchLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=10)),
                ('changed_on', models.DateTimeField(auto_now_add=True)),
                ('status', models.PositiveIntegerField(choices=[(1, 'Requested'), (2, 'Accepted'), (3, 'Declined'), (4, 'Done')])),
                ('paid_by_specialist', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='MatchProduct',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.RemoveField(
            model_name='matchacquired',
            name='client',
        ),
        migrations.RemoveField(
            model_name='matchacquired',
            name='sale_detail',
        ),
        migrations.RemoveField(
            model_name='matchacquired',
            name='specialist',
        ),
        migrations.RemoveField(
            model_name='matchacquiredfiles',
            name='match_acquired',
        ),
        migrations.RemoveField(
            model_name='matchacquiredlog',
            name='match_acquired',
        ),
        migrations.RenameField(
            model_name='match',
            old_name='speciality',
            new_name='category',
        ),
        migrations.RemoveField(
            model_name='match',
            name='product_type',
        ),
        migrations.RemoveField(
            model_name='queryplans',
            name='product_type',
        ),
        migrations.AddField(
            model_name='match',
            name='client',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='api.Client'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='match',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='match',
            name='declined_motive',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='match',
            name='paid_by_specialist',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='match',
            name='sale_detail',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='api.SaleDetail'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='match',
            name='specialist',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='api.Specialist'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='match',
            name='specialist_payment',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='api.Payment'),
        ),
        migrations.AddField(
            model_name='match',
            name='status',
            field=models.PositiveIntegerField(choices=[(1, 'Requested'), (2, 'Accepted'), (3, 'Declined'), (4, 'Done')], default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='match',
            name='subject',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='MatchAcquired',
        ),
        migrations.DeleteModel(
            name='MatchAcquiredFiles',
        ),
        migrations.DeleteModel(
            name='MatchAcquiredLog',
        ),
        migrations.AddField(
            model_name='matchlog',
            name='match_acquired',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api.Match'),
        ),
        migrations.AddField(
            model_name='matchfiles',
            name='match_acquired',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Match'),
        ),
    ]
