# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-03 21:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20171025_1822'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='photo',
            field=models.CharField(max_length=250, null=True),
        ),
    ]
