# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-16 21:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20171009_1258'),
    ]

    operations = [
        migrations.CreateModel(
            name='Quota',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.PositiveIntegerField()),
                ('end', models.DateTimeField()),
                ('start', models.DateTimeField()),
            ],
        ),
        migrations.RemoveField(
            model_name='purchase',
            name='product',
        ),
        migrations.AddField(
            model_name='product',
            name='purchases',
            field=models.ManyToManyField(db_table='products_purchase', to='api.Purchase'),
        ),
        migrations.AlterField(
            model_name='sellercontactnoefective',
            name='type_contact',
            field=models.CharField(choices=[('n', 'Natural'), ('b', 'Business')], max_length=1),
        ),
    ]
