# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-08-20 20:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20180820_1533'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='monthlyfee',
            name='payment',
        ),
        migrations.AddField(
            model_name='payment',
            name='monthly_fee',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='api.MonthlyFee'),
        ),
    ]
