# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-02-07 16:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20180129_1655'),
    ]

    operations = [
        migrations.AlterField(
            model_name='query',
            name='acquired_plan',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='api.QueryPlansAcquired'),
        ),
    ]
