# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-10 19:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20171009_1258'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ciiu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=4, unique=True)),
                ('description', models.CharField(max_length=255)),
            ],
        ),
        migrations.AlterField(
            model_name='countries',
            name='code_phone',
            field=models.CharField(max_length=4),
        ),
        migrations.AlterField(
            model_name='sellercontactnoefective',
            name='type_contact',
            field=models.CharField(choices=[('n', 'Natural'), ('b', 'Business')], max_length=1),
        ),
    ]
