# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-10 23:47
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20171103_1646'),
    ]
