# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-10 23:43
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20171103_1646'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchase',
            name='promotion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='api.Promotion'),
        ),
    ]
