# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-10-04 21:48
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20181004_1502'),
    ]

    operations = [
        migrations.CreateModel(
            name='MatchFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_url', models.CharField(max_length=500)),
                ('content_type', models.PositiveIntegerField(choices=[(1, 'Text'), (2, 'Image'), (3, 'Video'), (4, 'Voice'), (5, 'Document')])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('match_acquired', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Match')),
            ],
        ),
        migrations.RemoveField(
            model_name='matchfiles',
            name='match_acquired',
        ),
        migrations.DeleteModel(
            name='MatchFiles',
        ),
    ]
