# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-07-20 22:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_sellercontact_other_objection'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='queryplansacquired',
            name='is_chosen',
        ),
        migrations.AddField(
            model_name='queryplansclient',
            name='is_chosen',
            field=models.BooleanField(default=False),
        ),
    ]
