# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-02-08 17:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20180207_1145'),
    ]

    operations = [
        migrations.AddField(
            model_name='queryplansacquired',
            name='query_quantity',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
    ]
