# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-29 22:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20171110_1843'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='img_document_number',
            field=models.CharField(max_length=250, null=True),
        ),
    ]
