# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-07-27 21:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20180720_1720'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sellercontact',
            name='type_contact',
            field=models.PositiveIntegerField(choices=[(1, 'Effective'), (2, 'Non Effective'), (3, 'Effective paid')]),
        ),
    ]
