# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-16 21:37
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20171016_1631'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='seller_asigned',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='api.Seller'),
        ),
    ]
