# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-07-30 16:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20180720_1720'),
    ]

    operations = [
        migrations.AddField(
            model_name='queryplansmanage',
            name='count_queries',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
