# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-08-20 21:07
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20180820_1544'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='credit_card_exp_date',
        ),
    ]
