# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-16 20:47
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20171010_1443'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeclinedMotive',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('motive', models.CharField(max_length=255)),
            ],
        ),
        migrations.RemoveField(
            model_name='query',
            name='declined_motive',
        ),
        migrations.AlterField(
            model_name='query',
            name='status',
            field=models.CharField(choices=[('0', 'Requested'), ('1', 'Requested Derived'), ('2', 'Pending Response'), ('3', 'Pending Main Response'), ('4', 'Answered Main'), ('5', 'Answered'), ('6', 'Absolved Main'), ('7', 'Absolved')], max_length=1),
        ),
        migrations.AddField(
            model_name='declinedmotive',
            name='query_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api.Query'),
        ),
        migrations.AddField(
            model_name='declinedmotive',
            name='specialist_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api.Specialist'),
        ),
    ]
