# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-07-27 15:57
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20180720_1720'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='monthlyfee',
            name='sale_detail',
        ),
        migrations.AddField(
            model_name='monthlyfee',
            name='sale',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='api.Sale'),
            preserve_default=False,
        ),
    ]
