# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-17 22:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_auto_20171115_1713'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='sex',
            field=models.CharField(choices=[('n', 'Male'), ('b', 'Female')], max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='fee',
            name='status',
            field=models.CharField(choices=[('1', 'Pending'), ('2', 'Paid')], max_length=1),
        ),
        migrations.AlterField(
            model_name='sellercontactnoefective',
            name='type_contact',
            field=models.CharField(choices=[('n', 'Natural'), ('b', 'Bussiness')], max_length=1),
        ),
    ]
