# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-10-05 15:10
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_auto_20181004_1838'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='match',
            name='paid_by_specialist',
        ),
        migrations.AddField(
            model_name='match',
            name='payment_option_specialist',
            field=models.PositiveIntegerField(choices=[(1, 'paid_bank'), (2, 'make_discount')], null=True),
        ),
        migrations.AlterField(
            model_name='match',
            name='status',
            field=models.PositiveIntegerField(choices=[(1, 'Requested'), (2, 'Accepted'), (3, 'Declined'), (4, 'Pending_Paid_Client'), (5, 'Done')]),
        ),
        migrations.AlterField(
            model_name='matchfile',
            name='match',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api.Match'),
        ),
        migrations.AlterField(
            model_name='matchlog',
            name='status',
            field=models.PositiveIntegerField(choices=[(1, 'Requested'), (2, 'Accepted'), (3, 'Declined'), (4, 'Pending_Paid_Client'), (5, 'Done')]),
        ),
    ]
