# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-07-30 16:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_auto_20180727_1057'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='monthlyfee',
            name='reference_number',
        ),
        migrations.AlterField(
            model_name='monthlyfee',
            name='pay_before',
            field=models.DateField(null=True),
        ),
    ]
