# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-16 21:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_client_seller_asigned'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quota',
            name='end',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='quota',
            name='start',
            field=models.DateField(),
        ),
    ]
