# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-02-08 20:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_queryplansacquired_query_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='queryplansacquired',
            name='activation_date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='queryplansacquired',
            name='expiration_date',
            field=models.DateField(null=True),
        ),
    ]
