# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-08-21 15:21
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_remove_payment_credit_card_exp_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='authorization_date',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='payment',
            name='authorized_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='payment',
            name='observations',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
