# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-02-08 21:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_auto_20180208_1534'),
    ]

    operations = [
        migrations.AddField(
            model_name='queryplansacquired',
            name='plan_name',
            field=models.CharField(default='Minipack', max_length=50),
            preserve_default=False,
        ),
    ]
