# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-16 22:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_auto_20171016_1650'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='seller',
            name='end_date',
        ),
        migrations.RemoveField(
            model_name='seller',
            name='monthly_fee_contacts',
        ),
        migrations.RemoveField(
            model_name='seller',
            name='monthly_fee_plans',
        ),
        migrations.RemoveField(
            model_name='seller',
            name='start_date',
        ),
        migrations.AlterField(
            model_name='seller',
            name='count_month_contacts',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='seller',
            name='count_month_plans',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='seller',
            name='count_month_promotional',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='seller',
            name='monthly_promotional_plans',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
