# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-07-31 17:40
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_auto_20180730_1715'),
        ('api', '0006_auto_20180727_1627'),
    ]

    operations = [
    ]
