# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-16 23:32
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_auto_20171016_1650'),
        ('api', '0006_auto_20171016_1547'),
    ]

    operations = [
    ]
