# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-17 22:36
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_auto_20171117_1730'),
        ('api', '0007_auto_20171117_1726'),
    ]

    operations = [
    ]
