# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-08-23 16:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_auto_20180821_1021'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='status',
            field=models.PositiveIntegerField(choices=[(1, 'Pending'), (2, 'Accepted'), (3, 'Declined')], default=1),
        ),
    ]
