# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-22 16:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_merge_20171117_1736'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='sex',
            field=models.CharField(choices=[('m', 'Male'), ('f', 'Female')], max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='type_client',
            field=models.CharField(choices=[('n', 'Natural'), ('b', 'Business')], max_length=1),
        ),
        migrations.AlterField(
            model_name='sellercontactnoefective',
            name='type_contact',
            field=models.CharField(choices=[('n', 'Natural'), ('b', 'Business')], max_length=1),
        ),
    ]
