# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-10-05 21:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_matchfile_uploaded'),
    ]

    operations = [
        migrations.AddField(
            model_name='matchfile',
            name='file_preview_url',
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
