# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-08-27 21:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_auto_20180823_1119'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='status',
            field=models.PositiveIntegerField(choices=[(1, 'Pending'), (2, 'Paid')], default=1),
            preserve_default=False,
        ),
    ]
