# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-17 22:47
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_merge_20171016_1832'),
        ('api', '0008_auto_20171016_1752'),
    ]

    operations = [
    ]
