# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-08-02 14:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_merge_20180731_1240'),
    ]

    operations = [
        migrations.AlterField(
            model_name='objection',
            name='name',
            field=models.CharField(max_length=300),
        ),
    ]
