# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-02-12 22:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_queryplansacquired_plan_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='queryplansacquired',
            name='is_chosen',
            field=models.BooleanField(default=True),
        ),
    ]
