# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-18 21:05
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_auto_20171016_1752'),
        ('api', '0006_auto_20171016_1547'),
    ]

    operations = [
    ]
