# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-02-15 15:19
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_queryplansacquired_is_chosen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='query',
            name='specialist',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='api.Specialist'),
        ),
        migrations.AlterField(
            model_name='queryplansacquired',
            name='is_chosen',
            field=models.BooleanField(default=False),
        ),
    ]
