# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-18 22:27
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_merge_20171018_1605'),
        ('api', '0009_merge_20171017_1747'),
    ]

    operations = [
    ]
