# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-22 17:53
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20171110_2347'),
        ('api', '0009_auto_20171122_1115'),
    ]

    operations = [
    ]
