# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-19 15:51
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_merge_20171018_1727'),
    ]

    operations = [
        migrations.RenameField(
            model_name='quota',
            old_name='end',
            new_name='date',
        ),
        migrations.RemoveField(
            model_name='quota',
            name='start',
        ),
    ]
