# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-02-15 19:22
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_auto_20180215_1019'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='specialist',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='api.Specialist'),
        ),
    ]
