# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-08-31 21:54
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_auto_20180831_1252'),
    ]

    operations = [
        migrations.CreateModel(
            name='ParameterSeller',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number_month', models.PositiveIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('contacts_goal', models.PositiveIntegerField()),
                ('new_clients_goal', models.PositiveIntegerField()),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api.Seller')),
            ],
        ),
    ]
