# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-08-09 16:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_auto_20180809_1118'),
    ]

    operations = [
        migrations.AlterField(
            model_name='objection',
            name='name',
            field=models.CharField(max_length=300),
        ),
    ]
