# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-10-09 17:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_auto_20181009_1239'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='operation_number',
            field=models.CharField(blank=True, max_length=12, null=True, verbose_name='operation number'),
        ),
    ]
