# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-23 21:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_merge_20171122_1753'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='products_seller_no_billable',
            new_name='ProductsSellerNoBillable',
        ),
        migrations.AlterField(
            model_name='client',
            name='sex',
            field=models.CharField(choices=[('n', 'Male'), ('b', 'Female')], max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='type_client',
            field=models.CharField(choices=[('n', 'Natural'), ('b', 'Bussiness')], max_length=1),
        ),
        migrations.AlterField(
            model_name='sellercontactnoefective',
            name='type_contact',
            field=models.CharField(choices=[('n', 'Natural'), ('b', 'Bussiness')], max_length=1),
        ),
    ]
