# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-02-16 21:17
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_auto_20180215_1422'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seller',
            name='ciiu',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.Ciiu'),
        ),
    ]
