# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-02-19 15:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_auto_20180215_1422'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='code',
            field=models.CharField(default=1, max_length=45, verbose_name='code'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='message',
            name='nick',
            field=models.CharField(blank=True, max_length=45, verbose_name='nick'),
        ),
    ]
