# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-19 15:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_auto_20171018_1756'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quota',
            name='date',
            field=models.DateField(unique=True),
        ),
    ]
