# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-19 22:55
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_auto_20171019_1051'),
        ('api', '0012_auto_20171019_1028'),
    ]

    operations = [
    ]
