# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-02-21 19:23
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_auto_20180216_1617'),
        ('api', '0012_auto_20180219_1041'),
    ]

    operations = [
    ]
