# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-02-22 21:41
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_query_changed_on'),
    ]

    operations = [
        migrations.RenameField(
            model_name='queryplansacquired',
            old_name='cliente',
            new_name='client',
        ),
    ]
