# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-09-06 17:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_auto_20180905_1159'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sellercontact',
            name='agent_firstname',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='sellercontact',
            name='agent_lastname',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='sellercontact',
            name='business_name',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='sellercontact',
            name='commercial_reason',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='sellercontact',
            name='first_name',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='sellercontact',
            name='foreign_address',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='sellercontact',
            name='last_name',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='sellercontact',
            name='other_objection',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='sellercontact',
            name='position',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='sellercontact',
            name='profession',
            field=models.CharField(max_length=150, null=True),
        ),
    ]
