# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-29 16:31
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_client_commercial_reason'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='residence_country',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='residence', to='api.Countries'),
        ),
        migrations.AlterField(
            model_name='client',
            name='ciiu',
            field=models.CharField(max_length=4, null=True),
        ),
    ]
