# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-10-11 20:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_queryplansacquired_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='match',
            name='status',
            field=models.PositiveIntegerField(choices=[(1, 'Requested'), (2, 'Accepted'), (3, 'Declined'), (4, 'Pending paid client'), (5, 'Done'), (6, 'Voucher uploaded')]),
        ),
        migrations.AlterField(
            model_name='matchlog',
            name='status',
            field=models.PositiveIntegerField(choices=[(1, 'Requested'), (2, 'Accepted'), (3, 'Declined'), (4, 'Pending paid client'), (5, 'Done'), (6, 'Voucher uploaded')]),
        ),
        migrations.AlterField(
            model_name='payment',
            name='file_preview_url',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='payment',
            name='file_url',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
