# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-10-17 23:55
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_auto_20181011_1556'),
    ]

    operations = [
        migrations.AddField(
            model_name='sellercontact',
            name='code_cellphone',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='prefix_cellphone_contact', to='api.Countries'),
        ),
        migrations.AddField(
            model_name='sellercontact',
            name='code_telephone',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='prefix_telephone_contact', to='api.Countries'),
        ),
    ]
