# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-09-07 15:59
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_merge_20180906_1632'),
    ]

    operations = [
        migrations.RenameField(
            model_name='client',
            old_name='seller_asigned',
            new_name='seller_assigned',
        ),
    ]
