# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-29 22:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_auto_20171129_1131'),
    ]

    operations = [
        migrations.AddField(
            model_name='seller',
            name='ciiu',
            field=models.CharField(max_length=4, null=True),
        ),
    ]
