# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-02-26 15:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_merge_20180223_1708'),
    ]

    operations = [
        migrations.AlterField(
            model_name='query',
            name='changed_on',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
