# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-10-24 22:19
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_auto_20181017_1855'),
    ]

    operations = [
        migrations.AddField(
            model_name='sellercontact',
            name='client',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='api.Client'),
        ),
    ]
