# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-10-24 15:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_auto_20181017_1855'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='queryplans',
            name='non_billable',
        ),
        migrations.RemoveField(
            model_name='sellernonbillableplans',
            name='query_plans',
        ),
        migrations.AddField(
            model_name='queryplans',
            name='is_promotional',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='sellercontact',
            name='type_contact',
            field=models.PositiveIntegerField(choices=[(1, 'Effective'), (2, 'Non Effective'), (3, 'Effective paid'), (4, 'Promotional')]),
        ),
    ]
