# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-30 17:39
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_user_img_document_number'),
        ('api', '0015_seller_ciiu'),
    ]

    operations = [
    ]
