# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-09-07 16:15
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_auto_20180906_1212'),
        ('api', '0015_auto_20180907_1059'),
    ]

    operations = [
    ]
