# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-02-26 17:58
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_auto_20180226_1051'),
        ('api', '0015_merge_20180223_1716'),
    ]

    operations = [
    ]
