# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-10-25 20:59
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_auto_20181024_1008'),
        ('api', '0016_sellercontact_client'),
    ]

    operations = [
    ]
