# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-12-01 16:21
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_merge_20171130_1239'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='key',
            field=models.CharField(blank=True, max_length=45),
        ),
        migrations.AlterField(
            model_name='seller',
            name='zone',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='api.Zone'),
        ),
    ]
