# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-09-13 22:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_merge_20180907_1115'),
    ]

    operations = [
        migrations.AddField(
            model_name='queryplansacquired',
            name='queries_to_pay',
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='sale',
            name='status',
            field=models.PositiveIntegerField(choices=[(1, 'Unpaid'), (2, 'Progress'), (3, 'Paid')], default=1),
        ),
    ]
