# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-10-30 22:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_merge_20181025_1559'),
    ]

    operations = [
        migrations.AddField(
            model_name='sellercontact',
            name='is_assigned',
            field=models.BooleanField(default=False),
        ),
    ]
