# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-03-05 21:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_merge_20180226_1258'),
    ]

    operations = [
        migrations.AlterField(
            model_name='matchacquiredfiles',
            name='type_file',
            field=models.CharField(choices=[('0', 'Image'), ('1', 'Voice'), ('2', 'Document'), ('3', 'Video')], max_length=1),
        ),
        migrations.AlterField(
            model_name='messagefile',
            name='type_file',
            field=models.CharField(choices=[('0', 'Image'), ('1', 'Voice'), ('2', 'Document'), ('3', 'Video')], max_length=1),
        ),
    ]
