# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-09-17 14:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_auto_20180914_1438'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sellercontact',
            name='email',
        ),
        migrations.AddField(
            model_name='sellercontact',
            name='email_exact',
            field=models.CharField(max_length=150, null=True),
        ),
    ]
