# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-02-27 17:39
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_merge_20180226_1754'),
    ]

    operations = [
        migrations.AlterField(
            model_name='query',
            name='acquired_plan',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='api.QueryPlansAcquired'),
            preserve_default=False,
        ),
    ]
