# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-03-02 14:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_auto_20180227_1239'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='messagefile',
            name='message',
        ),
        migrations.AddField(
            model_name='message',
            name='file_type',
            field=models.CharField(blank=True, choices=[('0', 'Image'), ('1', 'Voice'), ('2', 'Document')], max_length=1),
        ),
        migrations.AddField(
            model_name='message',
            name='file_url',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='message',
            name='room',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='message',
            name='message',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='message',
            name='msg_type',
            field=models.CharField(blank=True, choices=[('q', 'query'), ('r', 'requery'), ('a', 'answer')], max_length=1),
        ),
        migrations.DeleteModel(
            name='MessageFile',
        ),
    ]
