# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-12-06 20:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_auto_20171204_1435'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='key',
            field=models.CharField(blank=True, max_length=90, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='ruc',
            field=models.CharField(blank=True, max_length=40, null=True, unique=True),
        ),
    ]
