# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-11-14 19:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_sellercontact_is_assigned'),
    ]

    operations = [
        migrations.AddField(
            model_name='monthlyfee',
            name='file_preview_url',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='monthlyfee',
            name='file_url',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='monthlyfee',
            name='status',
            field=models.PositiveIntegerField(choices=[(1, 'Pending'), (2, 'Paid'), (3, 'Checking payment')]),
        ),
    ]
