# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-09-17 15:35
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_auto_20180917_0937'),
        ('api', '0017_auto_20180913_1753'),
    ]

    operations = [
    ]
