# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-11-21 16:43
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0019_auto_20181114_1458'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactVisit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_visit', models.PositiveIntegerField(choices=[(1, 'Effective'), (2, 'Non Effective'), (4, 'Promotional')], max_length=1)),
                ('created_at', models.DateField(auto_now_add=True)),
                ('latitude', models.CharField(blank=True, max_length=45)),
                ('longitude', models.CharField(blank=True, max_length=45)),
                ('other_objection', models.CharField(blank=True, max_length=150, null=True)),
                ('contact', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api.SellerContact')),
                ('sale', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='api.Sale')),
            ],
        ),
        migrations.AddField(
            model_name='objectionslist',
            name='contact_visit',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='api.ContactVisit'),
            preserve_default=False,
        ),
    ]
