# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-03-02 15:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0019_auto_20180302_0956'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='file_type',
        ),
        migrations.AddField(
            model_name='message',
            name='content_type',
            field=models.CharField(choices=[('0', 'Text'), ('1', 'Image'), ('2', 'Voice'), ('3', 'Document')], default='0', max_length=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='matchacquiredfiles',
            name='type_file',
            field=models.CharField(choices=[('1', 'Image'), ('2', 'Voice'), ('3', 'Document')], max_length=1),
        ),
    ]
