# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-02-28 19:42
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0019_auto_20180228_1425'),
    ]

    operations = [
        migrations.DeleteModel(
                name='MessageFile',
        ),
        migrations.RemoveField(
            model_name='message',
            name='message_reference',
        ),
        migrations.AddField(
            model_name='message',
            name='reference',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ref', to='api.Message'),
        ),
    ]
