# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-09-17 21:16
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0019_merge_20180917_1514'),
        ('api', '0019_merge_20180917_1146'),
    ]

    operations = [
    ]
