# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-11-22 20:33
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0020_auto_20181121_1143'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactvisit',
            name='seller',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='api.Seller'),
        ),
        migrations.AlterField(
            model_name='contactvisit',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
