# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-12-07 17:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0020_auto_20171206_1714'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='foreign_address',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
