# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-03-02 22:09
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0020_auto_20180302_1035'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='nick',
        ),
    ]
