# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-03-09 15:23
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0021_remove_message_nick'),
        ('api', '0021_auto_20180228_1453'),
    ]

    operations = [
    ]
