# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-11-23 17:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0021_auto_20181122_1533'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='order',
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='category',
            name='status',
            field=models.PositiveIntegerField(choices=[(1, 'Enabled'), (2, 'Disabled')], default=1),
        ),
    ]
