# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-12-11 16:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0023_auto_20171207_1833'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='about',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='activity_description',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='foreign_address',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
