# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-03-13 20:53
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('api', '0023_auto_20180313_0944'),
    ]

    operations = [
        migrations.RunSQL(
            # 'source dump.sql'
            """CREATE OR REPLACE VIEW specialist_message_list AS
                SELECT
                  m.id,
                  u.photo,
                  u.nick,
                    max(m.created_at) AS date,
                  q.title,
                    count(1)          AS total,
                  q.client_id       AS client,
                  m.specialist_id as specialist
                FROM api_message m
                  JOIN api_query q
                    ON m.query_id = q.id
                  JOIN api_client c
                    ON q.client_id = c.user_ptr_id
                  JOIN api_user u
                    ON c.user_ptr_id = u.id
                WHERE m.viewed = 0
                GROUP BY q.client_id
                ORDER BY 4;"""
            )
    ]
