# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-03-13 20:53
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('api', '0023_auto_20180313_0944'),
    ]

    operations = [
        migrations.RunSQL("DROP PROCEDURE IF EXISTS SP_MESSAGES_LIST;"),
        migrations.RunSQL(
            # 'source dump.sql'
            """                
                CREATE PROCEDURE SP_MESSAGES_LIST(IN flag            INT,
                                                 IN p_client_id     INT,
                                                 IN p_spceialist_id INT)
                 BEGIN
                   IF flag = 1
                   THEN
                     #se busca la lista de un especialista
                    SELECT
                      max(m.id)         AS id,
                      u.photo,
                      u.nick,
                      max(m.created_at) AS date,
                      q.title,
                      q.client_id       AS client,
                      m.message,
                      q.specialist_id   AS specialist,
                      count(1)          AS total
                    FROM api_message m
                      JOIN api_query q
                        ON m.query_id = q.id
                      JOIN api_client c
                        ON q.client_id = c.user_ptr_id
                      JOIN api_user u
                        ON c.user_ptr_id = u.id
                    WHERE q.specialist_id = p_spceialist_id
                    GROUP BY q.client_id
                    ORDER BY 4;
                   ELSEIF flag = 2
                     THEN
                       # cuando buscamos por un determinado cliente
                       SELECT
                         max(m.id)         AS id,
                         u.photo,
                         u.nick,
                         max(m.created_at) AS date,
                         q.title,
                         count(1)          AS total,
                         q.client_id       AS client,
                         m.specialist_id   AS specialist
                       FROM api_message m
                         JOIN api_query q
                           ON m.query_id = q.id
                         JOIN api_client c
                           ON q.client_id = c.user_ptr_id
                         JOIN api_user u
                           ON c.user_ptr_id = u.id
                       WHERE q.client_id = p_client_id AND
                             m.viewed = 0
                       GROUP BY q.client_id
                       ORDER BY 4;
                   ELSE
                     SELECT
                       "None" AS id,
                       "None" AS photo,
                       "None" AS nick,
                       "None" AS date,
                       "None" AS title,
                       "None" AS total,
                       "None" AS client,
                       "None" AS specialist;
                   END IF;
                 END;
                """
            )
    ]
