# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-03-07 20:37
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0023_merge_20180305_1415'),
        ('api', '0023_merge_20180305_1036'),
    ]

    operations = [
    ]
