# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-03-15 21:38
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0024_merge_20180307_1537'),
        ('api', '0024_create_custom_index'),
    ]

    operations = [
    ]
