# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-12-11 20:41
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0024_auto_20171211_1157'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sellercontactnoefective',
            old_name='contact_bussinessname',
            new_name='bussiness_name',
        ),
        migrations.RenameField(
            model_name='sellercontactnoefective',
            old_name='contact_firstname',
            new_name='first_name',
        ),
        migrations.RenameField(
            model_name='sellercontactnoefective',
            old_name='contact_lastname',
            new_name='last_name',
        ),
        migrations.AddField(
            model_name='sellercontactnoefective',
            name='about',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='sellercontactnoefective',
            name='activity_description',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='sellercontactnoefective',
            name='address',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='api.Address'),
        ),
        migrations.AddField(
            model_name='sellercontactnoefective',
            name='birthdate',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='sellercontactnoefective',
            name='cellphone',
            field=models.CharField(blank=True, max_length=14, null=True),
        ),
        migrations.AddField(
            model_name='sellercontactnoefective',
            name='ciiu',
            field=models.CharField(blank=True, max_length=4),
        ),
        migrations.AddField(
            model_name='sellercontactnoefective',
            name='civil_state',
            field=models.CharField(choices=[('c', 'cohabiting'), ('e', 'separated'), ('m', 'married'), ('w', 'widower'), ('d', 'divorced'), ('s', 'single')], max_length=1, null=True),
        ),
        migrations.AddField(
            model_name='sellercontactnoefective',
            name='commercial_reason',
            field=models.CharField(max_length=45, null=True),
        ),
        migrations.AddField(
            model_name='sellercontactnoefective',
            name='economic_sector',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='api.EconomicSector'),
        ),
        migrations.AddField(
            model_name='sellercontactnoefective',
            name='email',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='sellercontactnoefective',
            name='institute',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='sellercontactnoefective',
            name='level_instruction',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='api.LevelInstruction'),
        ),
        migrations.AddField(
            model_name='sellercontactnoefective',
            name='nationality',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='api.Countries'),
        ),
        migrations.AddField(
            model_name='sellercontactnoefective',
            name='ocupation',
            field=models.CharField(blank=True, choices=[('0', 'Employer'), ('1', 'Independent worker'), ('2', 'Employee'), ('3', 'Worker'), ('4', 'Worker in a family business'), ('5', 'Home worker'), ('6', 'Other')], max_length=1),
        ),
        migrations.AddField(
            model_name='sellercontactnoefective',
            name='photo',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='sellercontactnoefective',
            name='position',
            field=models.CharField(max_length=45, null=True),
        ),
        migrations.AddField(
            model_name='sellercontactnoefective',
            name='profession',
            field=models.CharField(max_length=45, null=True),
        ),
        migrations.AddField(
            model_name='sellercontactnoefective',
            name='ruc',
            field=models.CharField(max_length=40, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='sellercontactnoefective',
            name='telephone',
            field=models.CharField(blank=True, max_length=14, null=True),
        ),
        migrations.AlterField(
            model_name='sellercontactnoefective',
            name='document_number',
            field=models.CharField(max_length=45),
        ),
        migrations.AlterField(
            model_name='sellercontactnoefective',
            name='latitude',
            field=models.CharField(blank=True, max_length=45),
        ),
        migrations.AlterField(
            model_name='sellercontactnoefective',
            name='longitude',
            field=models.CharField(blank=True, max_length=45),
        ),
    ]
