# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-12-13 16:38
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0023_user_status'),
        ('api', '0024_auto_20171211_1157'),
    ]

    operations = [
    ]
