# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-03-06 21:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0024_delete_messagefile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='content_type',
            field=models.CharField(choices=[('0', 'Text'), ('1', 'Image'), ('2', 'Video'), ('3', 'Voice'), ('4', 'Document')], max_length=1),
        ),
    ]
