# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-12-11 21:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0025_auto_20171211_1541'),
    ]

    operations = [
        migrations.AddField(
            model_name='sellercontactnoefective',
            name='sex',
            field=models.CharField(blank=True, choices=[('m', 'Male'), ('f', 'Female')], max_length=1),
        ),
    ]
