# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-03-23 21:22
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0025_specialistmessagelist_sp'),
        ('api', '0018_auto_20180305_2101'),
    ]

    operations = [
    ]
