# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-03-26 21:28
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0026_merge_20180323_2122'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MessageFile',
        ),
    ]
