# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-12-12 19:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0026_sellercontactnoefective_sex'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='street',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='user',
            name='code',
            field=models.CharField(max_length=45),
        ),
        migrations.AlterField(
            model_name='user',
            name='foreign_address',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
