# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-03-28 22:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0026_merge_20180323_2122'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='document_number',
            field=models.CharField(max_length=45, verbose_name='document number'),
        ),
        migrations.AlterField(
            model_name='user',
            name='ruc',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
    ]
