# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-04-06 20:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0027_auto_20180328_1720'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sellercontactnoefective',
            name='ruc',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
    ]
