# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-12-13 17:04
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0027_auto_20171212_1423'),
        ('api', '0025_merge_20171213_1138'),
    ]

    operations = [
    ]
