# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-12-15 18:02
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0028_merge_20171213_1204'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='code_cellphone',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='prefix_cellphone', to='api.Countries'),
        ),
        migrations.AddField(
            model_name='user',
            name='code_telephone',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='prefix_telephone', to='api.Countries'),
        ),
        migrations.AlterField(
            model_name='user',
            name='status',
            field=models.CharField(choices=[('0', 'pending'), ('1', 'activated'), ('2', 'rejected'), ('3', 'deactivated')], default='0', max_length=1),
        ),
    ]
