# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-12-15 20:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0028_merge_20171213_1204'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sellercontactnoefective',
            old_name='bussiness_name',
            new_name='business_name',
        ),
        migrations.AlterField(
            model_name='user',
            name='status',
            field=models.CharField(choices=[('0', 'pending'), ('1', 'activated'), ('2', 'rejected'), ('3', 'deactivated')], default='0', max_length=1),
        ),
    ]
