# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-12-15 18:03
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0029_auto_20171215_1302'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sellercontactnoefective',
            old_name='bussiness_name',
            new_name='business_name',
        ),
    ]
