# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-05-15 19:45
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0031_recoverypassword'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recoverypassword',
            old_name='key',
            new_name='code',
        ),
    ]
