# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-05-30 20:02
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0035_auto_add_group'),
        ('api', '0035_auto_20180530_1417'),
    ]

    operations = [
    ]
