# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-05-30 20:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0036_merge_20180530_1502'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sellercontactnoefective',
            name='ocupation',
            field=models.PositiveIntegerField(choices=[(1, 'Employer'), (2, 'Independent worker'), (3, 'Employee'), (4, 'Worker'), (5, 'Worker in a family business'), (6, 'Home worker'), (7, 'Other')], default=7, max_length=1, null=True),
        ),
    ]
