# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-05-30 23:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0040_auto_20180530_1813'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='ocupation',
            field=models.PositiveIntegerField(choices=[(1, 'Employer'), (2, 'Independent worker'), (3, 'Employee'), (4, 'Worker'), (5, 'Worker in a family business'), (6, 'Home worker'), (7, 'Other')], null=True),
        ),
    ]
