# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-06-05 19:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0043_specialistmessages_update'),
    ]

    operations = [
        migrations.CreateModel(
            name='SpecialistDecline',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField(blank=True)),
                ('query', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api.Query')),
                ('specialist', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api.Specialist')),
            ],
        ),
    ]
