# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-06-04 19:21
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0034_auto_20180530_1108'),
        ('api', '0043_specialistmessages_update'),
    ]

    operations = [
    ]
