# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-06-07 21:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0045_auto_20180605_1503'),
    ]

    operations = [
        migrations.AddField(
            model_name='query',
            name='available_requeries',
            field=models.PositiveIntegerField(default=30),
            preserve_default=False,
        ),
    ]
