# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-06-06 14:21
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0045_auto_20180605_1503'),
        ('api', '0044_merge_20180604_1421'),
    ]

    operations = [
    ]
