# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-06-07 22:40
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0046_query_available_requeries'),
        ('api', '0046_merge_20180606_0921'),
    ]

    operations = [
    ]
