# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-06-15 20:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0046_query_available_requeries'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='file_preview_url',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
