# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-06-18 15:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0047_message_file_preview_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='file_preview_url',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='message',
            name='file_url',
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
