# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-06-18 15:20
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0048_auto_20180618_1014'),
        ('api', '0047_merge_20180607_1740'),
    ]

    operations = [
    ]
