# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-06-22 19:50
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0048_auto_20180618_1014'),
    ]

    operations = [
        migrations.RenameField(
            model_name='query',
            old_name='calification',
            new_name='qualification',
        ),
    ]
