# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-07-10 16:07
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0049_auto_20180622_1450'),
    ]

    operations = [
        migrations.CreateModel(
            name='ObjectionsList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='SellerContact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=45, null=True)),
                ('last_name', models.CharField(max_length=55, null=True)),
                ('type_contact', models.PositiveIntegerField(choices=[(1, 'Non-effective'), (2, 'Effective to pay'), (3, 'Effective')])),
                ('type_client', models.CharField(choices=[('n', 'Natural'), ('b', 'Business')], max_length=1)),
                ('document_type', models.PositiveIntegerField(choices=[(1, 'DNI'), (2, 'Passport'), (3, 'Foreign Card')])),
                ('document_number', models.CharField(max_length=45)),
                ('email', models.CharField(max_length=150, null=True)),
                ('civil_state', models.CharField(choices=[('c', 'cohabiting'), ('e', 'separated'), ('m', 'married'), ('w', 'widower'), ('d', 'divorced'), ('s', 'single')], max_length=1, null=True)),
                ('birthdate', models.DateField(null=True)),
                ('institute', models.CharField(blank=True, max_length=100, null=True)),
                ('activity_description', models.CharField(blank=True, max_length=255, null=True)),
                ('photo', models.CharField(max_length=250, null=True)),
                ('about', models.CharField(blank=True, max_length=255, null=True)),
                ('cellphone', models.CharField(blank=True, max_length=14, null=True)),
                ('telephone', models.CharField(blank=True, max_length=14, null=True)),
                ('ocupation', models.PositiveIntegerField(choices=[(1, 'Employer'), (2, 'Independent worker'), (3, 'Employee'), (4, 'Worker'), (5, 'Worker in a family business'), (6, 'Home worker'), (7, 'Other')], default=7, null=True)),
                ('profession', models.CharField(max_length=45, null=True)),
                ('business_name', models.CharField(max_length=45, null=True)),
                ('commercial_reason', models.CharField(max_length=45, null=True)),
                ('agent_firstname', models.CharField(max_length=45, null=True)),
                ('agent_lastname', models.CharField(max_length=45, null=True)),
                ('sex', models.CharField(blank=True, choices=[('m', 'Male'), ('f', 'Female')], max_length=1)),
                ('latitude', models.CharField(blank=True, max_length=45)),
                ('longitude', models.CharField(blank=True, max_length=45)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('position', models.CharField(max_length=45, null=True)),
                ('ruc', models.CharField(blank=True, max_length=40, null=True)),
                ('address', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='api.Address')),
                ('ciiu', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.Ciiu')),
                ('economic_sector', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='api.EconomicSector')),
                ('level_instruction', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='api.LevelInstruction')),
                ('nationality', models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='api.Countries')),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api.Seller')),
            ],
        ),
        migrations.RemoveField(
            model_name='sellercontactnoefective',
            name='address',
        ),
        migrations.RemoveField(
            model_name='sellercontactnoefective',
            name='ciiu',
        ),
        migrations.RemoveField(
            model_name='sellercontactnoefective',
            name='economic_sector',
        ),
        migrations.RemoveField(
            model_name='sellercontactnoefective',
            name='level_instruction',
        ),
        migrations.RemoveField(
            model_name='sellercontactnoefective',
            name='nationality',
        ),
        migrations.RemoveField(
            model_name='sellercontactnoefective',
            name='objection',
        ),
        migrations.RemoveField(
            model_name='sellercontactnoefective',
            name='seller',
        ),
        migrations.DeleteModel(
            name='SellerContactNoEfective',
        ),
        migrations.AddField(
            model_name='objectionslist',
            name='contact',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api.SellerContact'),
        ),
        migrations.AddField(
            model_name='objectionslist',
            name='objection',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api.Objection'),
        ),
    ]
