# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-07-10 22:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0051_auto_20180710_1240'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sellercontact',
            name='about',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='sellercontact',
            name='activity_description',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='sellercontact',
            name='photo',
            field=models.CharField(max_length=250, null=True),
        ),
    ]
