# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-07-09 16:03
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0051_queryplansclient_queryplansmanage'),
    ]

    operations = [
        migrations.AddField(
            model_name='queryplansmanage',
            name='email_receiver',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='queryplansmanage',
            name='receiver',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='api.Client'),
        ),
    ]
