# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-07-12 16:07
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0052_auto_20180710_1727'),
    ]

    operations = [
        migrations.AddField(
            model_name='sellercontact',
            name='residence_country',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='residence_contact', to='api.Countries', verbose_name='residence country contact'),
        ),
    ]
