# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-07-10 21:17
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0049_merge_20180618_1020'),
        ('api', '0052_auto_20180709_1103'),
    ]

    operations = [
    ]
