# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-07-12 13:40
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0053_merge_20180710_1617'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='ocupation',
            field=models.PositiveIntegerField(choices=[(1, 'Employer'), (2, 'Independent worker'), (3, 'Employee'), (4, 'Worker'), (5, 'Worker in a family business'), (6, 'Home worker'), (7, 'Other')], null=True),
        ),
        migrations.AlterField(
            model_name='matchacquired',
            name='status',
            field=models.PositiveIntegerField(choices=[(1, 'Requested'), (2, 'Accepted'), (3, 'Declined')]),
        ),
        migrations.AlterField(
            model_name='matchacquiredfiles',
            name='type_file',
            field=models.PositiveIntegerField(choices=[(2, 'Image'), (3, 'Voice'), (4, 'Document')]),
        ),
        migrations.AlterField(
            model_name='matchacquiredlog',
            name='status',
            field=models.PositiveIntegerField(choices=[(1, 'Requested'), (2, 'Accepted'), (3, 'Declined')]),
        ),
        migrations.AlterField(
            model_name='message',
            name='content_type',
            field=models.PositiveIntegerField(choices=[(1, 'Text'), (2, 'Image'), (3, 'Video'), (4, 'Voice'), (5, 'Document')]),
        ),
        migrations.AlterField(
            model_name='monthlyfee',
            name='status',
            field=models.PositiveIntegerField(choices=[(1, 'Pending'), (2, 'Paid')]),
        ),
        migrations.AlterField(
            model_name='payment',
            name='status',
            field=models.PositiveIntegerField(choices=[(1, 'Pending'), (2, 'Accepted'), (3, 'Declined')]),
        ),
        migrations.AlterField(
            model_name='query',
            name='status',
            field=models.PositiveIntegerField(choices=[(1, 'Requested'), (2, 'Accepted'), (3, 'Answered'), (4, 'To score'), (5, 'Absolved')]),
        ),
        migrations.AlterField(
            model_name='querylogs',
            name='status_log',
            field=models.PositiveIntegerField(choices=[(1, 'Requested'), (2, 'Accepted'), (3, 'Answered'), (4, 'To score'), (5, 'Absolved')]),
        ),
        migrations.AlterField(
            model_name='queryplansclient',
            name='status',
            field=models.PositiveIntegerField(choices=[(1, 'Active'), (2, 'Deactive'), (3, 'Processing')]),
        ),
        migrations.AlterField(
            model_name='queryplansmanage',
            name='new_acquired_plan',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='api.QueryPlansAcquired'),
        ),
        migrations.AlterField(
            model_name='queryplansmanage',
            name='status',
            field=models.PositiveIntegerField(choices=[(1, 'Active'), (2, 'Deactive'), (3, 'Processing')]),
        ),
        migrations.AlterField(
            model_name='sellercontactnoefective',
            name='document_type',
            field=models.PositiveIntegerField(choices=[(1, 'DNI'), (2, 'Passport'), (3, 'Foreign Card')]),
        ),
        migrations.AlterField(
            model_name='sellercontactnoefective',
            name='ocupation',
            field=models.PositiveIntegerField(choices=[(1, 'Employer'), (2, 'Independent worker'), (3, 'Employee'), (4, 'Worker'), (5, 'Worker in a family business'), (6, 'Home worker'), (7, 'Other')], default=7, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='document_type',
            field=models.PositiveIntegerField(choices=[(1, 'DNI'), (2, 'Passport'), (3, 'Foreign Card')], verbose_name='type document'),
        ),
        migrations.AlterField(
            model_name='user',
            name='status',
            field=models.PositiveIntegerField(choices=[(1, 'Pending'), (2, 'Activate'), (3, 'Reject'), (4, 'Deactivated')], default=1),
        ),
    ]
