# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-07-12 23:05
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0053_sellercontact_residence_country'),
        ('api', '0054_auto_20180712_0840'),
    ]

    operations = [
    ]
